module.exports = {
  backdropBlur: ({ theme }) => theme('blur'),
  backdropBrightness: ({ theme }) => theme('brightness'),
  backdropContrast: ({ theme }) => theme('contrast'),
  backdropGrayscale: ({ theme }) => theme('grayscale'),
  backdropHueRotate: ({ theme }) => theme('hueRotate'),
  backdropInvert: ({ theme }) => theme('invert'),
  backdropOpacity: ({ theme }) => theme('opacity'),
  backdropSaturate: ({ theme }) => theme('saturate'),
  backdropSepia: ({ theme }) => theme('sepia'),
  backgroundColor: ({ theme }) => theme('colors'),
  backgroundOpacity: ({ theme }) => theme('opacity'),
  backgroundPosition: {
    bottom: 'bottom',
    center: 'center',
    left: 'left',
    'left-bottom': 'left bottom',
    'left-top': 'left top',
    right: 'right',
    'right-bottom': 'right bottom',
    'right-top': 'right top',
    top: 'top',
  },
  backgroundSize: {
    auto: 'auto',
    cover: 'cover',
    contain: 'contain',
  },
};
