name: CI/CD to Unithon Cluster

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Create .env file
      run: |
        echo RELEASE_ENV=\"development\" >> .env

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/unithon-frontend-dev:${{ github.run_number }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitOps repository
      uses: actions/checkout@v3
      with:
        repository: dokdo2013/haenu-cluster
        token: ${{ secrets.GITOPS_TOKEN }}
        path: gitops

    - name: Update deployment tag in GitOps repo
      run: |
        IMAGE_NAME="unithon-frontend-dev"
        APP_NAME="frontend-dev"
        cd gitops/apps/unithon/${APP_NAME}
        sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${{ github.run_number }}|g" deployment.yaml
        git config user.name "dokdo2013"
        git config user.email "hyeonwoo5342@gmail.com"
        git add .
        git commit -m "feat(${APP_NAME}): Build and deploy new commit ${{ github.run_number }}"
        git push
